# Generated by Django 3.2.14 on 2022-07-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteid', models.CharField(max_length=10, verbose_name='NoteID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('author', models.CharField(max_length=30, verbose_name='Author')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
